version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: frontend
